### PR TITLE
20240307 backend convert users&auth to js

### LINKED ISSUE #40: implement user authentication

### LINKED ISSUE #51: Convert Backend from TypeScript to JavaScript
### Description 

Using TSC to compile resulted in extra transcribed JavaScript files. This caused bloat and unnecessary issues. By converting the TypeScript files to JavaScript files permanently, ideally the issues will be resolved.

#### Tasks

- [x] Remove TypeScript Dependencies

- [x] Convert TypeScript Files to JavaScript

- [x] Update Build and Run Scripts

- [x] Refactor TypeScript Specific Code

- [x] Update Linting and Formatting Tools

### PR DESCRIPTION
**Pull request by SeanEstrella**
This pull request is for the conversion from TypeScript to JavaScript in the Backend. 

It resolves #51

### CODE REVIEW

**Comment by xgarcia17** [comment]
I'm not able to run the backend because of some errors, like a variable not being defined before its use. Could you take a look at it please?

**Comment by SeanEstrella** [comment]
package.json in express-backend was updated to be able to run with the proper scripts

**Comment by SeanEstrella** [comment]
To enhance the clarity and maintain consistency with the recent modularization efforts in our backend, I've merged changes from the Main branch into this one. This update includes:

- Renaming files in the routes folder to end with '-routes' for better clarity.

- Converting all TypeScript files to JavaScript to align with our current technology stack.

- Updating the express-backend package to include the appropriate scripts, ensuring our setup remains robust and up-to-date.

These changes aim to streamline our codebase and improve overall project maintainability.

**Comment by jangomax** [comment]
lgtm merged

**Pull request merged**
